SeguroCalifornias/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from django_registration.backends.one_step.views import RegistrationView

from core.views import IndexTemplateView
from users.forms import CustomUserForm
from users.views import change_password

urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/register/",
        RegistrationView.as_view(
            form_class=CustomUserForm,
            success_url="/",
        ), name="django_registration_register"),
    path("accounts/",
        include("django_registration.backends.one_step.urls")),
    path("accounts/",
        include("django.contrib.auth.urls")),
    path("accounts/change-password/", change_password, name="change_password"),
    path("", IndexTemplateView.as_view(), name="home"),
    path("compania/", include("company.urls"), name="cmp"),
    path("clientes/", include("client.urls"), name="cliente"),
    path("seguros/", include("insurance.urls"), name="seguro"),
    path("reaseguros/", include("reinsurance.urls"), name="reaseguro"),
    path("siniestros/", include("sinister.urls"), name="siniestro")
]

client/urls.py
from django.urls import path

from .views import *

app_name = "cliente"
urlpatterns = [
    path('', ShowClientView.as_view(), name="lista-cliente"),
    path('exportar/xls/', export_clients_xls, name="xlsexport-cliente"),
    path('exportar/pdf/', PDFClientView.as_view(), name="pdfexport-cliente"),
    path('exportar/pdf/<int:pk>/', PDFDetailClientView.as_view(), name="pdfexport-cliente-det"),
    path('agregar/', CreateClientView.as_view(), name="agregar-cliente"),
    path('detalles/<int:id>/', DetailClientView.as_view(), name="detail-cliente"),
    path('editar/<int:id>/', UpdateClientView.as_view(), name="update-cliente"),
    path('deshabilitar/<int:id>/', client_disable, name="disable-cliente"),
    path('habilitar/<int:id>/', client_enable, name="enable-cliente"),
]

insurance/urls.py
from django.urls import path

from .views import (CreateCoverageView, CreateInsuranceView, CreatePlanView,
                    DetailCoverageView, DetailInsuranceView, DetailPlanView,
                    ShowCoverageView, ShowInsuranceView, ShowPlanView,
                    UpdateCoverageView)

app_name = "cov"
urlpatterns = [
    path('coberturas/', ShowCoverageView.as_view(), name="lista-cov"),
    path('coberturas/<int:id>/', DetailCoverageView.as_view(), name="detail-cov"),
    path('coberturas/<int:id>/editar/', UpdateCoverageView.as_view(), name="update-cov"),
    path('coberturas/agregar/', CreateCoverageView.as_view(), name="crear-cov"),
    path('planes/', ShowPlanView.as_view(), name="lista-plan"),
    path('planes/<int:id>/', DetailPlanView.as_view(), name="detail-plan"),
    path('planes/agregar/', CreatePlanView.as_view(), name="crear-plan"),
    path('', ShowInsuranceView.as_view(), name="lista-ins"),
    path('<int:id>/', DetailInsuranceView.as_view(), name="detail-ins"),
    path('agregar/', CreateInsuranceView.as_view(), name="crear-ins"),
]

insurance/forms.py
from crispy_forms.helper import FormHelper
from crispy_forms.layout import HTML, Column, Layout, MultiField, Row, Submit
from django import forms
from django.forms.widgets import CheckboxSelectMultiple

from .models import Coverage, Insurance, Plan


class CoverageForm(forms.ModelForm):

    class Meta:
        model = Coverage
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(CoverageForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.layout = Layout(
            Row(
                Column('estado', css_class='form-group col-md-12 text-right '),
            ),
            Row(
                Column('nombre', css_class='form-group col-md-12'),
            ),
            Row(
                Column('moneda', css_class='form-group col-md-2'),
                Column('prima', css_class='form-group col-md-2'),
                Column('riesgo_reas', css_class='form-group col-md-3'),
                Column('cob_reas', css_class='form-group col-md-5'),
                css_class='form-row'
            ),
            HTML("<h5>Opciones</h5>"),
            Row(
                Column('tasa_cob', css_class='form-group col-md-4'),
                Column('prima_cob', css_class='form-group col-md-4'),
                Column('suma_aseg_cob', css_class='form-group col-md-4'),
            ),
            Row(
                Column('suma_aseg_min', css_class='form-group col-md-3'),
                Column('suma_aseg_max', css_class='form-group col-md-3'),
                Column('suma_aseg_min_int', css_class='form-group col-md-3'),
                Column('suma_aseg_sin', css_class='form-group col-md-3'),
            ),
            HTML("<h5>Opciones</h5>"),
            Row(
                Column('edad_min', css_class='form-group col-md-2'),
                Column('edad_max', css_class='form-group col-md-2'),
                Column('per_esp_an', css_class='form-group col-md-2'),
                Column('per_esp_mes', css_class='form-group col-md-2'),
                Column('porc_gast_adq', css_class='form-group col-md-4'),
            ),
            HTML("<h5>Opciones</h5>"),
            Row(
                Column('por_ant', css_class='form-group col-md-2'),
                Column('mnt_max_ant', css_class='form-group col-md-2'),
                Column('porc_deduc', css_class='form-group col-md-2'),
                Column('mnt_deduc', css_class='form-group col-md-2'),
                Column('copago', css_class='form-group col-md-2'),
                Column('porc_copago', css_class='form-group col-md-2'),
            ),
            HTML("<h5>Opciones</h5>"),
            Row(
                Column('cob_basica', css_class='form-group col-md-12'),
                Column('dev_prima', css_class='form-group col-md-12'),
                Column('apl_factor_x', css_class='form-group col-md-12'),
                Column('apl_sami', css_class='form-group col-md-12'),
                Column('acu_sumrs', css_class='form-group col-md-12'),
                Column('acu_primrs', css_class='form-group col-md-12'),
            ),
        )
        self.fields['riesgo_reas'].label = "Riesgo de Reaseguro"
        self.fields['cob_reas'].label = "Cobro de Reaseguro"
        self.fields['tasa_cob'].label = "Tasa de Cobertura"
        self.fields['prima_cob'].label = "Prima de Cobertura"
        self.fields['suma_aseg_cob'].label = "Suma Asegurada de Cobertura"
        self.fields['suma_aseg_min'].label = "Suma Asegurada Minima"
        self.fields['suma_aseg_max'].label = "Suma Asegurada Maxima"
        self.fields['suma_aseg_min_int'].label = "Suma Asegurada Minima Int."
        self.fields['suma_aseg_sin'].label = "Suma Asegurada Alerta Siniestros"
        self.fields['suma_aseg_min'].label = "Suma Asegurada Minima"


class PlanForm(forms.ModelForm):

    class Meta:
        model = Plan
        exclude = ['fc', 'fm']

    def __init__(self, *args, **kwargs):
        super(PlanForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.layout = Layout(
            Row(
                Column('estado', css_class='form-group col-md-12 text-right')
            ),
            Row(
                Column('codigo', css_class='form-group col-md-2'),
                Column('nombre', css_class='form-group col-md-10'),
            ),
            Row(
                Column('tipo_plan', css_class='form-group col-md-4'),
                Column('moneda', css_class='form-group col-md-4'),
                Column('dias_retro', css_class='form-group col-md-4'),
            ),
            Row(
                Column('tiṕos_plan', css_class='form-group col-md-2'),
                Column('mod_seg', css_class='form-group col-md-3'),
                Column('tipo_pol', css_class='form-group col-md-2'),
                Column('cod_tempo', css_class='form-group col-md-2'),
                Column('niv_com', css_class='form-group col-md-3'),
            ),
            Row(
                Column('porc_gast_adm', css_class='form-group col-md-3'),
                Column('porc_utilidad', css_class='form-group col-md-2'),
                Column('porc_max_comi', css_class='form-group col-md-2'),
                Column('plazo_acept_sin', css_class='form-group col-md-3'),
                Column('indisput', css_class='form-group col-md-2'),
                Column('porc_gastos_adq', css_class='form-group col-md-3'),
                Column('durac_contra', css_class='form-group col-md-2')
            ),
            Row(
                Column('cobert', css_class='form-group col-md-12'),
            )
        )
        self.fields['cobert'].label = "Coberturas"
        self.fields['cobert'].widget = CheckboxSelectMultiple()
        self.fields['cobert'].queryset = Coverage.objects.all()
        self.fields['tipo_plan'].label = "Tipo de Plan"
        self.fields['dias_retro'].label = "Dias de Retroactivo"
        self.fields['tiṕos_plan'].label = "SubPlan"
        self.fields['mod_seg'].label = "Modalidad del Seguro"
        self.fields['tipo_pol'].label = "Tipo de Poliza"
        self.fields['cod_tempo'].label = "Duracion"
        self.fields['niv_com'].label = "Nivel Comercial"
        self.fields['porc_gast_adm'].label = "% Gastos de Administracion"
        self.fields['porc_utilidad'].label = "% Utilidad"
        self.fields['porc_max_comi'].label = "% Maximo Comision"
        self.fields['plazo_acept_sin'].label = "Plazo Aceptacion Siniestros"
        self.fields['indisput'].label = "Indisputabilidad"
        self.fields['porc_gastos_adq'].label = "% Gastos Adquisicion"
        self.fields['durac_contra'].label = "Duracion Contrato"


class InsuranceForm(forms.ModelForm):

    class Meta:
        model = Insurance
        exclude = ['fc', 'fm']

    def __init__(self, *args, **kwargs):
        super(InsuranceForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_tag = False
        self.helper.layout = Layout(
            Row(
                Column('estado', css_class='form-group col-md-12 text-right')
            ),
            Row(
                Column('codigo', css_class='form-group col-md-2'),
                Column('nombre', css_class='form-group col-md-8'),
                Column('tipo_cont', css_class='form-group col-md-2'),
            ),
            Row(
                Column('dias_canc', css_class='form-group col-md-2'),
                Column('cod_tipo_plan', css_class='form-group col-md-2'),
                Column('plan_pago', css_class='form-group col-md-2'),
                Column('tipo_riesgo', css_class='form-group col-md-2'),
            ),
            Row(
                Column('renov_aut', css_class='form-group col-md-4'),
            ),
            Row(
                Column('plan', css_class='form-group col-md-12'),
            )

        )
        self.fields['tipo_cont'].label = "Tipo de Contabilidad"
        self.fields['dias_canc'].label = "Dias Cancelacion"
        self.fields['cod_tipo_plan'].label = "Tipo de Plan"
        self.fields['plan_pago'].label = "Plan de Pago"
        self.fields['tipo_riesgo'].label = "Tipo de Riesgo"
        self.fields['renov_aut'].label = "Renovacion Automatica de Poliza"
        self.fields['plan'].label = "Planes"
        self.fields['plan'].widget = CheckboxSelectMultiple()
        self.fields['plan'].queryset = Plan.objects.all()

insurance/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.http import Http404, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse, reverse_lazy
from django.views.generic import CreateView, DetailView, ListView, UpdateView

from .forms import CoverageForm, InsuranceForm, PlanForm
from .models import Coverage, Insurance, Plan


class ShowCoverageView(LoginRequiredMixin, ListView):
    model = Coverage
    template_name = "coberturas/index.html"
    context_object_name = "obj"
    login_url = "login"


class DetailCoverageView(LoginRequiredMixin, DetailView):
    model = Coverage
    template_name = "coberturas/detail.html"
    context_object_name = "obj"
    pk_url_kwarg = "id"
    login_url = "login"


class CreateCoverageView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = Coverage
    template_name = "coberturas/create.html"
    form_class = CoverageForm
    success_url = reverse_lazy('cov:lista-cov')
    login_url = 'login'

    def get_success_message(self, cleaned_data):
        print(cleaned_data)
        return "La Cobertura Ha Sido Creada Exitosamente"

    def form_invalid(self, form):
        print(form.errors)
        return self.render_to_response(self.get_context_data(form=form))

    # def form_valid(self, form):
    #     risk = form.save(commit=False)
    #     risk.save()
    #
    #     success_url = reverse('cov:lista-cov')
    #     success_message = "La Cobertura Ha Sido Creada Exitosamente"
    #
    #     return HttpResponseRedirect(success_url, success_message)


class UpdateCoverageView(LoginRequiredMixin, UpdateView):
    model = Coverage
    form_class = CoverageForm
    template_name = "coberturas/update.html"
    pk_url_kwarg = "id"
    context_object_name = 'cli'
    login_url = "login"
    success_url = reverse_lazy('cov:lista-cov')


class ShowPlanView(LoginRequiredMixin, ListView):
    model = Plan
    template_name = "planes/index.html"
    context_object_name = "obj"
    login_url = "login"


class DetailPlanView(LoginRequiredMixin, DetailView):
    model = Plan
    template_name = "planes/detail.html"
    context_object_name = "obj"
    pk_url_kwarg = "id"
    login_url = "login"


class CreatePlanView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = Plan
    template_name = "planes/create.html"
    form_class = PlanForm
    success_url = reverse_lazy('cov:lista-plan')
    login_url = 'login'

    def get_success_message(self, cleaned_data):
        print(cleaned_data)
        return "El Plan Ha Sido Creado Exitosamente"


class ShowInsuranceView(LoginRequiredMixin, ListView):
    model = Insurance
    template_name = "seguros/index.html"
    context_object_name = "obj"
    login_url = "login"


class DetailInsuranceView(LoginRequiredMixin, DetailView):
    model = Insurance
    template_name = "seguros/detail.html"
    context_object_name = "obj"
    pk_url_kwarg = "id"
    login_url = "login"


class CreateInsuranceView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = Insurance
    template_name = "seguros/create.html"
    form_class = InsuranceForm
    success_url = reverse_lazy('cov:lista-ins')
    login_url = 'login'

    def get_success_message(self, cleaned_data):
        print(cleaned_data)
        return "El Seguro Ha Sido Creado Exitosamente"

insurance/templates/seguros/create.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %} Agregar Seguro{% endblock%}
{% block css %}
    <style>
        label{
            color: #3a3b45;
            font-weight:700;
        }
    </style>
{% endblock %}
{% block content %}
    <form method="POST" >
     {% csrf_token %}
    <div class="">
              <div class="card border-left-success shadow h-100 py-2">
                <div class="card-body">
                  <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                      <div class="text-xs font-weight-bold text-success text-uppercase mb-2"> <h5>Nuevo Seguro</h5></div>

                            {% crispy form %}
                        <br>
                            <button type="submit" class="btn btn-success"> <i class="fa fa-save"></i> Agregar</button>

                    </div>

                  </div>
                </div>
              </div>
            </div>
</form>
{% endblock %}

insurance/templates/seguros/detail.html
{% extends 'base.html' %} {% block title %} Detalle Seguro {{ obj.nombre }}{% endblock%} {% block css %}
    <style>
    .table-bordered {
  border: 3px solid #001e6c !important; }
    </style>
{% endblock %} {% block content %}
<div class="card mb-3">
    <h5 class="card-header font-weight-bolder text-gray-900">Detalles del Seguro {{ obj.codigo }}</h5>
    <div class="card-body">
        <table class="table table-striped table-bordered table-hover text-center">
            <thead class="thead-primary">
                <th>Nombre</th>
                <th>Tipo de Contabilidad</th>
                <th>Estado</th>
            </thead>
            <tbody>
                <tr>
                    <td>{{ obj.nombre }}</td>
                    <td>{{ obj.tipo_cont }}</td>
                    <td>{{ obj.estado|yesno:"Activo,Inactivo" }}</td>
                </tr>
            </tbody>
        </table>
        <h4 class="text-primary font-weight-bolder">Planes</h4>
        <table class="table table-striped table-bordered table-hover text-center">
            <thead class="thead-primary">
                <th>ID</th>
                <th>Codigo</th>
                <th>Nombre</th>
                <th>Tipo de Plan</th>
                <th>Moneda</th>
                <th>Dias Retro</th>
                <th>Estado</th>
            </thead>
            <tbody>
                {% for item in obj.plan.all %}
                <tr>
                    <td><a href="{% url 'cov:detail-plan' item.id %}">{{ item.id }}</a></td>
                    <td>{{ item.codigo }}</td>
                    <td>{{ item.nombre }}</td>
                    <td>{{ item.tipo_plan }}</td>
                    <td>{{ item.moneda }}</td>
                    <td>{{ item.dias_retro }}</td>
                    <td>{{ item.estado|yesno:"Activo,Inactivo" }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        <br />
        <div class="row">
            <div class="col-md-12">
                <div class="row">
                    <div class="col-md-3">
                        <div class="form-group">
                            <label>Dias Cancelacion Falta de Pago: </label>
                            <p class="text-gray-900 font-weight-bold">{{ obj.dias_canc }}</p>
                        </div>
                    </div>

                    <div class="col-md-2">
                        <div class="form-group">
                            <label>Ramo del Plan: </label>
                            <p class="text-gray-900 font-weight-bold">{{ obj.plan_pago.nombre }}</p>
                        </div>
                    </div>

                    <div class="col-md-2">
                        <div class="form-group">
                            <label>Plan de Pagos: </label>
                            <p class="text-gray-900 font-weight-bold">{{ obj.plan_pago.nombre }}</p>
                        </div>
                    </div>

                    <div class="col-md-2">
                        <div class="form-group">
                            <label>Tipo de Riesgo: </label>
                            <p class="text-gray-900 font-weight-bold">{{ obj.tipo_riesgo }}</p>
                        </div>
                    </div>

                    <div class="col-md-3">
                        <div class="form-group">
                            <label>Renovacion Aut Polizas: </label>
                            <p class="text-gray-900 font-weight-bold">{{ obj.renov_aut|yesno:"Si,No" }}</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %} {% block js %} {% endblock %}

insurance/templates/seguros/index.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Seguros{% endblock%}
{% block css %}
    <style>
        .illustration{
            display: block;
            margin-left: auto;
            margin-right: auto;
            width: 801px;
            height: 632px;
            background: url({% static 'img/undraw_empty_xct9.svg' %});
            background-size: cover;
        }
    </style>
{% endblock %}
{% block content %}
    {% if messages %}
         <div class=" alert alert-success alert-dismissible fade show" role="alert">
      {% for message in messages %}
        {{ message }}
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
      {% endfor %}
         </div>
    {% endif %}
    <div class="card shadow mb-4">
        <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                  <h4 class="m-0 font-weight-bold text-gray-900">Seguros</h4>
                  <div class="dropdown no-arrow">
                    <a class="btn btn-success tn-block" href="{% url 'cov:crear-ins' %}" role="button" >
                      <i class="fas fa-plus fa-sm fa-fw "></i>
                        Agregar
                    </a>
                  </div>

                </div>

        <div class="card-body">
                  {% if not obj %}
                       <div class="col-md-12">
                          <h2 class="font-weight-bold text-center">No hay seguros</h2>
                          <div class="illustration"></div>
                      </div>
                    {% else %}

                <table class="table table-striped table-hover text-center">

                    <thead class="thead-primary">
                    <th>ID</th>
                    <th>Codigo</th>
                    <th>Nombre</th>
                    <th>Tipo de Contabilidas</th>
                    <th>Estado</th>
                    <th class="all">Acciones</th>
                    </thead>
                    <tbody>
                    {% for item in obj %}
                        <tr>
                        <td>{{ item.id }}</td>
                        <td>{{ item.codigo }}</td>
                        <td>{{ item.nombre }}</td>
                        <td>{{ item.tipo_cont }}</td>
                        <td>{{ item.estado|yesno:"Activo,Inactivo" }}</td>
                        <td>

                            <a href="{% url 'cov:detail-ins' item.id %}" class="btn btn-sm btn-info mr-2" role="button"><i class="fa fa-eye"></i></a>
                                {% if perms.reinsurance.can_edit_reinsurancerisk %}
                            <a href="{% url 'cov:update-cov' item.id %}" class="btn btn-sm btn-warning mr-2 " role="button"><i class="fa fa-edit"></i></a>
                                {% endif %}

                            <a href="{% url 'cliente:disable-cliente' item.id %}" class="btn btn-sm btn-danger mr-2" role="button"><i class="fa fa-trash-alt"></i></a>


                        </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
                {% endif %}
                </div>
    </div>
{% endblock %}
{% block js %}
    <script>
        // Call the dataTables jQuery plugin
        $(document).ready(function () {
            $('.table').DataTable({
                "language": {
                    "sProcessing": "Procesando...",
                    "sLengthMenu": "Mostrar _MENU_ registros",
                    "sZeroRecords": "No se encontraron resultados",
                    "sEmptyTable": "Ningún dato disponible en esta tabla",
                    "sInfo": "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
                    "sInfoEmpty": "Mostrando registros del 0 al 0 de un total de 0 registros",
                    "sInfoFiltered": "(filtrado de un total de _MAX_ registros)",
                    "sInfoPostFix": "",
                    "sSearch": "Buscar:",
                    "sUrl": "",
                    "sInfoThousands": ",",
                    "sLoadingRecords": "Cargando...",
                    "oPaginate": {
                        "sFirst": "<span class='fa fa-angle-double-left'></span>",
                        "sLast": "<span class='fa fa-angle-double-right'></span>",
                        "sNext": "<span class='fa fa-angle-right'></span>",
                        "sPrevious": "<span class='fa fa-angle-left'></span>"
                    },
                    "oAria": {
                        "sSortAscending": ": Activar para ordenar la columna de manera ascendente",
                        "sSortDescending": ": Activar para ordenar la columna de manera descendente"
                    }
                }
            });
        });
    </script>
{% endblock %}