SeguroCalifornias/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from django_registration.backends.one_step.views import RegistrationView

from core.views import IndexTemplateView
from users.forms import CustomUserForm
from users.views import change_password

urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/register/",
        RegistrationView.as_view(
            form_class=CustomUserForm,
            success_url="/",
        ), name="django_registration_register"),
    path("accounts/",
        include("django_registration.backends.one_step.urls")),
    path("accounts/",
        include("django.contrib.auth.urls")),
    path("accounts/change-password/", change_password, name="change_password"),
    path("", IndexTemplateView.as_view(), name="home"),
    path("compania/", include("company.urls"), name="cmp"),
    path("clientes/", include("client.urls"), name="cliente"),
    path("seguros/", include("insurance.urls"), name="seguro"),
    path("reaseguros/", include("reinsurance.urls"), name="reaseguro"),
    path("siniestros/", include("sinister.urls"), name="siniestro")
]

client/urls.py
from django.urls import path

from .views import *

app_name = "cliente"
urlpatterns = [
    path('', ShowClientView.as_view(), name="lista-cliente"),
    path('exportar/xls/', export_clients_xls, name="xlsexport-cliente"),
    path('exportar/pdf/', PDFClientView.as_view(), name="pdfexport-cliente"),
    path('exportar/pdf/<int:pk>/', PDFDetailClientView.as_view(), name="pdfexport-cliente-det"),
    path('agregar/', CreateClientView.as_view(), name="agregar-cliente"),
    path('detalles/<int:id>/', DetailClientView.as_view(), name="detail-cliente"),
    path('editar/<int:id>/', UpdateClientView.as_view(), name="update-cliente"),
    path('deshabilitar/<int:id>/', client_disable, name="disable-cliente"),
    path('habilitar/<int:id>/', client_enable, name="enable-cliente"),
]

sinister/urls.py
from django.urls import path

from .views import (CreateConceptView, CreateMedicineGroupView,
                    CreateMedicineView, CreateTransactionView,
                    DetailMedicineGroupView, DetailMedicineView,
                    PDFMedicineView, ShowConceptView, ShowMedicineGroupView,
                    ShowMedicineView, ShowTransactionView,
                    UpdateMedicineGroupView, UpdateMedicineView,
                    export_medicinegroup_xls, export_medicinelist_xls)

app_name = "sin"
urlpatterns = [
    path('conceptos/', ShowConceptView.as_view(), name="lista-concept"),
    path('conceptos/crear/', CreateConceptView.as_view(), name="crear-concept"),
    path('transacciones/', ShowTransactionView.as_view(), name="lista-trans"),
    path('transacciones/crear/', CreateTransactionView.as_view(), name="crear-trans"),
    path('medicamentos/', ShowMedicineGroupView.as_view(), name="lista-medi"),
    path('medicamentos/crear/', CreateMedicineGroupView.as_view(), name="crear-medi"),
    path('medicamentos/editar/<int:id>/', UpdateMedicineGroupView.as_view(), name="update-medi"),
    path('medicamentos/<int:id>/', DetailMedicineGroupView.as_view(), name="detail-medi"),
    path('exportar/xls/', export_medicinegroup_xls, name="xlsexport-medi"),
    path('exportar/pdf/', PDFMedicineView.as_view(), name="pdfexport-medi"),
    path('medicamentos/lista/', ShowMedicineView.as_view(), name="lista-medilist"),
    path('medicamentos/lista/exportar/xls/', export_medicinelist_xls, name="xlsexport-medilist"),
    path('medicamentos/lista/crear/', CreateMedicineView.as_view(), name="crear-medilist"),
    path('medicamentos/lista/<int:id>', DetailMedicineView.as_view(), name="detail-medilist"),
    path('medicamentos/lista/editar/<int:id>/', UpdateMedicineView.as_view(), name="update-medilist"),
]

sinister/forms.py
from crispy_forms.helper import FormHelper
from crispy_forms.layout import HTML, Column, Layout, MultiField, Row, Submit
from django.forms import ModelForm
from django.forms.widgets import CheckboxSelectMultiple

from .models import Concept, Medicine, MedicineGroup, Transaction


class ConceptForm(ModelForm):

    class Meta:
        model = Concept
        fields = "__all__"

    def __init__(self, *args, **kwargs):
        super(ConceptForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.layout = Layout(
            Row(
                Column('tipo_con', css_class='form-group col-md-12'),
            ),
            Row(
                Column('codigo', css_class='form-group col-md-3'),
                Column('nombre', css_class='form-group col-md-9'),
            )
        )
        self.fields['tipo_con'].label = "Tipo de Conceptos"


class TransactionForm(ModelForm):

    class Meta:
        model = Transaction
        fields = "__all__"

    def __init__(self, *args, **kwargs):
        super(TransactionForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.layout = Layout(
            Row(
                Column('estado', css_class='form-group col-md-12 text-right '),
            ),
            Row(
                Column('codigo', css_class='form-group col-md-3'),
                Column('nombre', css_class='form-group col-md-9'),
            ),
            Row(
                Column('donde_applica', css_class='form-group col-md-3'),
                Column('signo', css_class='form-group col-md-3'),
            ),
            Row(
                Column('conceptos', css_class='form-group col-md-12'),
            ),
        )
        self.fields['donde_applica'].label = "Donde Aplica?"
        self.fields['conceptos'].widget = CheckboxSelectMultiple()
        self.fields['conceptos'].queryset = Concept.objects.all()


class MedicineForm(ModelForm):

    class Meta:
        model = Medicine
        fields = "__all__"

    def __init__(self, *args, **kwargs):
        super(MedicineForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.layout = Layout(
            Row(
                Column('codigo_ean', css_class='form-group col-md-2'),
                Column('nombre', css_class='form-group col-md-6'),
                Column('princ_activo', css_class='form-group col-md-2'),
                Column('precio_max', css_class='form-group col-md-2'),
            ),
            Row(
                Column('forma', css_class='form-group col-md-2'),
                Column('presentacion', css_class='form-group col-md-2'),
                Column('via_admin', css_class='form-group col-md-2'),
                Column('qty', css_class='form-group col-md-2'),
                Column('concentra', css_class='form-group col-md-2'),
                Column('um', css_class='form-group col-md-2'),
            ),
            Row(
                Column('lab', css_class='form-group col-md-12'),
            ),
            Row(
                Column('indicaciones', css_class='form-group col-md-6'),
                Column('contra', css_class='form-group col-md-6'),
            ),


        )
        self.fields['codigo_ean'].label = "Codigo EAN"
        self.fields['princ_activo'].label = "Principio Activo"
        self.fields['precio_max'].label = "Precio Maximo"
        self.fields['via_admin'].label = "Via Administracion"
        self.fields['qty'].label = "Cantidad"
        self.fields['concentra'].label = "Concentracion"
        self.fields['um'].label = "Unidad de Medida"
        self.fields['lab'].label = "Laboratorio"
        self.fields['contra'].label = "ContraIndicaciones"


class MedicineGroupForm(ModelForm):

    class Meta:
        model = MedicineGroup
        fields = "__all__"

    def __init__(self, *args, **kwargs):
        super(MedicineGroupForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.layout = Layout(
            Row(
                Column('codigo', css_class='form-group col-md-2'),
                Column('nombre', css_class='form-group col-md-6'),
                Column('precio_min', css_class='form-group col-md-2'),
                Column('precio_max', css_class='form-group col-md-2'),
            ),
            Row(
                Column('obsv', css_class='form-group col-md-12'),
            ),
            Row(
                Column('req_auth', css_class='form-group col-md-3'),
                Column('auth_med', css_class='form-group col-md-3'),
                Column('auth_med_area', css_class='form-group col-md-3'),
                Column('auth_call_center', css_class='form-group col-md-3'),
            ),
            Row(
                Column('medicamento', css_class='form-group col-md-12'),
            )
        )
        self.fields['precio_min'].label = "Precio Minimo"
        self.fields['precio_max'].label = "Precio Maximo"
        self.fields['obsv'].label = "Observaciones"
        self.fields['req_auth'].label = "Requiere Autorizacion"
        self.fields['auth_med'].label = "Autoriza Medico Especialista"
        self.fields['auth_med_area'].label = "Autoriza Area Medica"
        self.fields['auth_call_center'].label = "Autoriza Call Center"
        self.fields['medicamento'].label = "Medicamentos"
        self.fields['medicamento'].widget = CheckboxSelectMultiple()
        self.fields['medicamento'].queryset = Medicine.objects.all()

sinister/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.http import HttpResponse
from django.urls import reverse_lazy
from django.utils import timezone
from django.views.generic import (CreateView, DetailView, ListView, UpdateView,
                                  View)

from client.render import Render

from .forms import (ConceptForm, MedicineForm, MedicineGroupForm,
                    TransactionForm)
from .models import Concept, Medicine, MedicineGroup, Transaction
from .resources import MedicineListResource, MedicineResource


class ShowConceptView(LoginRequiredMixin, ListView):
    model = Concept
    template_name = "conceptos/index.html"
    context_object_name = "obj"
    login_url = "login"


class CreateConceptView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = Concept
    template_name = "conceptos/create.html"
    form_class = ConceptForm
    success_url = reverse_lazy('sin:lista-concept')
    login_url = 'login'

    def get_success_message(self, cleaned_data):
        print(cleaned_data)
        return "El Concepto Ha Sido Creada Exitosamente"


class ShowTransactionView(LoginRequiredMixin, ListView):
    model = Transaction
    template_name = "transacciones/index.html"
    context_object_name = "obj"
    login_url = "login"


class CreateTransactionView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = Transaction
    template_name = "transacciones/create.html"
    form_class = TransactionForm
    success_url = reverse_lazy('sin:lista-trans')
    login_url = 'login'

    def get_success_message(self, cleaned_data):
        print(cleaned_data)
        return "La Transaccion Ha Sido Creada Exitosamente"


class ShowMedicineView(LoginRequiredMixin, ListView):
    model = Medicine
    template_name = "medicinas/index.html"
    context_object_name = "obj"
    login_url = "login"


def export_medicinelist_xls(request):
    client_resource = MedicineListResource()
    dataset = client_resource.export()
    response = HttpResponse(dataset.xls, content_type='application/vnd.ms-excel')
    response['Content-Disposition'] = 'attachment; filename="ListaMedicamentos".xls"'

    return response


class CreateMedicineView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = Medicine
    template_name = "medicinas/create.html"
    form_class = MedicineForm
    success_url = reverse_lazy('sin:lista-medilist')
    login_url = 'login'

    def get_success_message(self, cleaned_data):
        print(cleaned_data)
        return "El Medicamento Ha Sido Creado Exitosamente"


class DetailMedicineView(LoginRequiredMixin, DetailView):
    model = Medicine
    template_name = "medicinas/detail.html"
    context_object_name = "obj"
    pk_url_kwarg = "id"
    login_url = "login"


class UpdateMedicineView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = Medicine
    template_name = "medicinas/update.html"
    form_class = MedicineForm
    pk_url_kwarg = "id"
    context_object_name = 'medl'
    success_url = reverse_lazy('sin:lista-medilist')
    login_url = "login"

    def get_success_message(self, cleaned_data):
        print(cleaned_data)
        return "El Medicamento Ha Sido Actualizado Exitosamente"


class ShowMedicineGroupView(LoginRequiredMixin, ListView):
    model = MedicineGroup
    template_name = "grupomedicinas/index.html"
    context_object_name = "obj"
    login_url = "login"


def export_medicinegroup_xls(request):
    client_resource = MedicineResource()
    dataset = client_resource.export()
    response = HttpResponse(dataset.xls, content_type='application/vnd.ms-excel')
    response['Content-Disposition'] = 'attachment; filename="GrupoMedicamentos.xls"'

    return response


class PDFMedicineView(LoginRequiredMixin, View):
    login_url = "login"

    def get(self, request):
        meds = MedicineGroup.objects.all()
        today = timezone.now()
        params = {
            'today': today,
            'clients': meds,
            'request': request
        }
        return Render.render("grupomedicinas/pdfdetail.html", params)


class CreateMedicineGroupView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = MedicineGroup
    template_name = "grupomedicinas/create.html"
    form_class = MedicineGroupForm
    success_url = reverse_lazy('sin:lista-medi')
    login_url = 'login'

    def get_success_message(self, cleaned_data):
        print(cleaned_data)
        return "El Grupo de Medicamento Ha Sido Creado Exitosamente"


class DetailMedicineGroupView(LoginRequiredMixin, DetailView):
    model = MedicineGroup
    template_name = "grupomedicinas/detail.html"
    context_object_name = "obj"
    pk_url_kwarg = "id"
    login_url = "login"


class UpdateMedicineGroupView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = MedicineGroup
    template_name = "grupomedicinas/update.html"
    form_class = MedicineGroupForm
    pk_url_kwarg = "id"
    context_object_name = 'med'
    success_url = reverse_lazy('sin:lista-medi')
    login_url = "login"

    def get_success_message(self, cleaned_data):
        print(cleaned_data)
        return "El Grupo de Medicamento Ha Sido Actualizado Exitosamente"

sinister/templates/medicinas/create.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %} Agregar Medicamento{% endblock%}
{% block css %}
    <style>
        label{
            color: #3a3b45;
            font-weight:700;
        }
    </style>
{% endblock %}
{% block content %}
    <form method="POST" >
     {% csrf_token %}
    <div class="">
              <div class="card border-left-success shadow h-100 py-2">
                <div class="card-body">
                  <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                      <div class="text-xs font-weight-bold text-success text-uppercase mb-2"> <h5>Nuevo Medicamento</h5></div>

                            {% crispy form %}
                        <br>
                            <button type="submit" class="btn btn-success"> <i class="fa fa-save"></i> Agregar</button>

                    </div>

                  </div>
                </div>
              </div>
            </div>
</form>
{% endblock %}

sinister/templates/medicinas/detail.html
{% extends 'base.html' %} {% block title %} Detalle Medicamento {{ obj.nombre }}{% endblock %} {% block css %}
    <style>

    </style>
{% endblock %} {% block content %}
    <div class="card mb-3">
        <h5 class="card-header font-weight-bolder text-gray-900">Detalles del Medicamento</h5>
        <div class="card-body">
            <div class="row">
                <div class="col-md-3">
                    <div class="form-group">
                        <label for="obsv" class="">Codigo EAN: </label>
                        <p class="text-gray-900 font-weight-bold">{{ obj.codigo_ean }}</p>
                    </div>
                </div>

                <div class="col-md-3">
                    <div class="form-group">
                        <label>Nombre del Medicamento: </label>
                        <p class="text-gray-900 font-weight-bold">{{ obj.nombre }}</p>
                    </div>
                </div>

                <div class="col-md-2">
                    <div class="form-group">
                        <label>Principio Activo: </label>
                        <p class="text-gray-900 font-weight-bold">{{ obj.princ_activo }}</p>
                    </div>
                </div>

                <div class="col-md-2">
                    <div class="form-group">
                        <label>Precio Maximo: </label>
                        <p class="text-gray-900 font-weight-bold"> $ {{ obj.precio_max }}</p>
                    </div>
                </div>

                <div class="col-md-2">
                     <div class="form-group">
                        <label>Laboratorio: </label>
                        <p class="text-gray-900 font-weight-bold">{{ obj.lab.nombre }}</p>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-2">
                    <div class="form-group">
                        <label>Forma: </label>
                        <p class="text-gray-900 font-weight-bold">{{ obj.forma }}</p>
                    </div>
                </div>

                <div class="col-md-2">
                    <div class="form-group">
                        <label>Presentacion: </label>
                        <p class="text-gray-900 font-weight-bold">{{ obj.presentacion }}</p>
                    </div>
                </div>

                <div class="col-md-2">
                    <div class="form-group">
                        <label>Via Administracion: </label>
                        <p class="text-gray-900 font-weight-bold">{{ obj.via_admin }}</p>
                    </div>
                </div>

                <div class="col-md-2">
                    <div class="form-group">
                        <label>Cantidad: </label>
                        <p class="text-gray-900 font-weight-bold">{{ obj.qty }}</p>
                    </div>
                </div>

                <div class="col-md-2">
                    <div class="form-group">
                        <label>Concentracion: </label>
                        <p class="text-gray-900 font-weight-bold">{{ obj.concentra }}</p>
                    </div>
                </div>

                <div class="col-md-2">
                    <div class="form-group">
                        <label>Unidad de Medida: </label>
                        <p class="text-gray-900 font-weight-bold">{{ obj.um }}</p>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                     <div class="form-group">
                        <label for="obsv" class="">Indicaciones: </label>
                        <textarea id="obsv" class="form-control text-gray-900 font-weight-bold" rows="7" readonly>{{ obj.indicaciones }}</textarea>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-md-12">
                     <div class="form-group">
                        <label for="obsv" class="">ContraIndicaciones: </label>
                        <textarea id="obsv" class="form-control text-gray-900 font-weight-bold" rows="7" readonly>{{ obj.contra }}</textarea>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %} {% block js %} {% endblock %}

sinister/templates/medicinas/index.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Lista Medicamentos{% endblock %}
{% block css %}
    <style>
        .illustration {
            display: block;
            margin-left: auto;
            margin-right: auto;
            width: 801px;
            height: 632px;
            background: url({% static 'img/undraw_empty_xct9.svg' %});
            background-size: cover;
        }
    </style>
{% endblock %}
{% block content %}
    {% if messages %}
        <div class=" alert alert-success alert-dismissible fade show" role="alert">
            {% for message in messages %}
                {{ message }}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            {% endfor %}
        </div>
    {% endif %}

    <div class="card shadow mb-4">
        <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
            <h4 class="m-0 font-weight-bold text-gray-900">Lista Medicamentos</h4>
            <div class="dropdown no-arrow">
                <a class="btn btn-success tn-block" href="{% url 'sin:crear-medilist' %}" role="button">
                    <i class="fas fa-plus fa-sm fa-fw "></i>
                    Agregar
                </a>
            </div>
        </div>

        <div class="card-body">
            {% if not obj %}
                <div class="col-md-12">
                    <h2 class="font-weight-bold text-center">No Hay Medicamentos</h2>
                    <div class="illustration"></div>
                </div>
            {% else %}
                <div class="col-md-6 mb-3 pl-0">

                    <a class="btn btn-outline-brand-excel" href="{% url 'sin:xlsexport-medilist' %}" role="button">
                        <i class="fas fa-file-excel fa-fw "></i>
                        Excel
                    </a>
                    <a class="btn btn-outline-brand-google" href="{% url 'sin:pdfexport-medi' %}" role="button" target="_blank">
                        <i class="fas fa-file-pdf fa-fw "></i>
                        PDF
                    </a>
                </div>
                <table id="table" class="table table-striped table-hover text-center">
                    <thead class="thead-primary">
                    <th>ID</th>
                    <th>Codigo EAN</th>
                    <th>Nombre</th>
                    <th>Principio Activo</th>
                    <th>Precio Maximo</th>
                    <th class="all">Acciones</th>
                    </thead>
                    <tbody>
                    {% for item in obj %}
                        <tr>
                            <td>{{ item.id }}</td>
                            <td>{{ item.codigo_ean }}</td>
                            <td>{{ item.nombre }}</td>
                            <td>{{ item.princ_activo }}</td>
                            <td>{{ item.precio_max }}</td>
                            <td>

                                <a href="{% url 'sin:detail-medilist' item.id %}" class="btn btn-sm btn-info mr-2"
                                   role="button"><i class="fa fa-eye"></i></a>
                                {% if perms.reinsurance.can_edit_reinsurancerisk %}
                                    <a href="{% url 'sin:update-medilist' item.id %}" class="btn btn-sm btn-warning mr-2 "
                                       role="button"><i class="fa fa-edit"></i></a>
                                {% endif %}

                                <a href="{% url 'cliente:disable-cliente' item.id %}" class="btn btn-sm btn-danger mr-2"
                                   role="button"><i class="fa fa-trash-alt"></i></a>


                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            {% endif %}
        </div>
    </div>
{% endblock %}
{% block js %}
    <script>
        // Call the dataTables jQuery plugin
        $(document).ready(function () {
            $('.table').DataTable({
                "language": {
                    "sProcessing": "Procesando...",
                    "sLengthMenu": "Mostrar _MENU_ registros",
                    "sZeroRecords": "No se encontraron resultados",
                    "sEmptyTable": "Ningún dato disponible en esta tabla",
                    "sInfo": "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
                    "sInfoEmpty": "Mostrando registros del 0 al 0 de un total de 0 registros",
                    "sInfoFiltered": "(filtrado de un total de _MAX_ registros)",
                    "sInfoPostFix": "",
                    "sSearch": "Buscar:",
                    "sUrl": "",
                    "sInfoThousands": ",",
                    "sLoadingRecords": "Cargando...",
                    "oPaginate": {
                        "sFirst": "<span class='fa fa-angle-double-left'></span>",
                        "sLast": "<span class='fa fa-angle-double-right'></span>",
                        "sNext": "<span class='fa fa-angle-right'></span>",
                        "sPrevious": "<span class='fa fa-angle-left'></span>"
                    },
                    "oAria": {
                        "sSortAscending": ": Activar para ordenar la columna de manera ascendente",
                        "sSortDescending": ": Activar para ordenar la columna de manera descendente"
                    }
                }
            });
        });
    </script>
{% endblock %}

sinister/templates/medicinas/update.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %} Editar Medicamento{% endblock%}
{% block content %}
    <form method="POST" >
     {% csrf_token %}
    <div class="">
              <div class="card border-left-warning shadow h-100 py-2">
                <div class="card-body">
                  <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                      <div class="text-xs font-weight-bold text-warning text-uppercase mb-2"> <h5>Editar Medicamento</h5></div>

                            {% crispy form %}
                        <br>
                            <button type="submit" class="btn btn-warning"> <i class="fa fa-save"></i> Editar</button>

                    </div>

                  </div>
                </div>
              </div>
            </div>
</form>
{% endblock %}