SeguroCalifornias/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from django_registration.backends.one_step.views import RegistrationView

from core.views import IndexTemplateView
from users.forms import CustomUserForm
from users.views import change_password

urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/register/",
        RegistrationView.as_view(
            form_class=CustomUserForm,
            success_url="/",
        ), name="django_registration_register"),
    path("accounts/",
        include("django_registration.backends.one_step.urls")),
    path("accounts/",
        include("django.contrib.auth.urls")),
    path("accounts/change-password/", change_password, name="change_password"),
    path("", IndexTemplateView.as_view(), name="home"),
    path("compania/", include("company.urls"), name="cmp"),
    path("clientes/", include("client.urls"), name="cliente"),
    path("seguros/", include("insurance.urls"), name="seguro"),
    path("reaseguros/", include("reinsurance.urls"), name="reaseguro"),
    path("siniestros/", include("sinister.urls"), name="siniestro")
]

client/urls.py
from django.urls import path

from .views import *

app_name = "cliente"
urlpatterns = [
    path('', ShowClientView.as_view(), name="lista-cliente"),
    path('exportar/xls/', export_clients_xls, name="xlsexport-cliente"),
    path('exportar/pdf/', PDFClientView.as_view(), name="pdfexport-cliente"),
    path('exportar/pdf/<int:pk>/', PDFDetailClientView.as_view(), name="pdfexport-cliente-det"),
    path('agregar/', CreateClientView.as_view(), name="agregar-cliente"),
    path('detalles/<int:id>/', DetailClientView.as_view(), name="detail-cliente"),
    path('editar/<int:id>/', UpdateClientView.as_view(), name="update-cliente"),
    path('deshabilitar/<int:id>/', client_disable, name="disable-cliente"),
    path('habilitar/<int:id>/', client_enable, name="enable-cliente"),
]

client/models.py
from django.db import models


class TipoDocOf(models.Model):
    nombre = models.CharField(max_length=30)

    def __str__(self):
        return self.nombre

    class Meta:
        verbose_name_plural = "Tipos de Documentos Oficiales"


class Client(models.Model):
    nombre = models.CharField(max_length=30)
    apep = models.CharField(max_length=30)
    apem = models.CharField(max_length=30)
    direccion = models.CharField(max_length=150)
    no_int = models.CharField(max_length=10, null=True)
    no_ext = models.CharField(max_length=10)
    colonia = models.CharField(max_length=50)
    ciudad = models.CharField(max_length=20)
    estado = models.CharField(max_length=20)
    cp = models.CharField(max_length=5)
    pais = models.CharField(max_length=20)
    tel = models.CharField(max_length=50)
    email = models.EmailField()
    tipodoc = models.ForeignKey(TipoDocOf, on_delete=models.CASCADE)
    nodocof = models.CharField(max_length=15)
    fc = models.DateTimeField(auto_now_add=True)
    fm = models.DateTimeField(auto_now=True)
    estado = models.BooleanField(default=True)

    def __str__(self):
        return '{} - {} {} {}'.format(self.id, self.apep, self.apem, self.nombre)

    class Meta:
        verbose_name_plural = "Clientes"

client/forms.py
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Column, Layout, Row, Submit
from django import forms

from .models import Client


class ClientForm(forms.ModelForm):

    class Meta:
        model = Client
        fields = ['nombre', 'apep', 'apem', 'direccion', 'no_int', 'no_ext', 'colonia', 'ciudad', 'cp',
                  'pais', 'tel', 'email', 'tipodoc', 'nodocof', 'estado']

    def __init__(self, *args, **kwargs):
        super(ClientForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.layout = Layout(
            Row(
                Column('nombre', css_class='form-group col-md-4'),
                Column('apep', css_class='form-group col-md-4'),
                Column('apem', css_class='form-group col-md-4'),
                css_class='form-row'
            ),
            'direccion',
            Row(
                Column('no_int', css_class='form-group col-md-2'),
                Column('no_ext', css_class='form-group col-md-2'),
                Column('colonia', css_class='form-group col-md-2'),
                Column('ciudad', css_class='form-group col-md-2'),
                Column('cp', css_class='form-group col-md-2'),
                Column('pais', css_class='form-group col-md-2'),
                css_class='form-row'
            ),
            Row(
                Column('tel', css_class='form-group col-md-6'),
                Column('email', css_class='form-group col-md-6'),
                css_class='form-row'
            ),
            Row(
                Column('tipodoc', css_class='form-group col-md-6'),
                Column('nodocof', css_class='form-group col-md-6'),
                css_class='form-row'
            ),
            'estado'
        )
        self.fields['nombre'].label = "Nombre"
        self.fields['apep'].label = "Apellido Paterno"
        self.fields['apem'].label = "Apellido Materno"
        self.fields['no_int'].label = "No. Interior"
        self.fields['no_ext'].label = "No. Exterior"
        self.fields['cp'].label = "Codigo Postal"
        self.fields['tel'].label = "Telefono"
        self.fields['tipodoc'].label = "Documento Oficial"
        self.fields['nodocof'].label = "No. del Documento Oficial"

client/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import redirect, render
from django.template.loader import get_template, render_to_string
from django.urls import reverse
from django.utils import timezone
from django.views.generic import (CreateView, DetailView, ListView, UpdateView,
                                  View)

from .forms import ClientForm
from .models import Client
from .render import Render
from .resources import ClientResource


class ShowClientView(LoginRequiredMixin, ListView):
    model = Client
    template_name = "clientes/index.html"
    context_object_name = "obj"
    login_url = "login"


def export_clients_xls(request):
    client_resource = ClientResource()
    dataset = client_resource.export()
    response = HttpResponse(dataset.xls, content_type='application/vnd.ms-excel')
    response['Content-Disposition'] = 'attachment; filename="Clientes.xls"'

    return response


class PDFClientView(LoginRequiredMixin, View):
    login_url = "login"

    def get(self, request):
        clients = Client.objects.all()
        today = timezone.now()
        params = {
            'today': today,
            'clients': clients,
            'request': request
        }
        return Render.render("clientes/pdfdetail.html", params)


class PDFDetailClientView(LoginRequiredMixin, View):
    login_url = "login"

    def get(self, request, pk):
        clientdet = Client.objects.get(id=pk)
        today = timezone.now()
        params = {
            'today': today,
            'clientdet': clientdet,
            'request': request
        }
        return Render.render("clientes/pdfdetails.html", params)


class CreateClientView(LoginRequiredMixin, CreateView):
    model = Client
    form_class = ClientForm
    template_name = 'clientes/create.html'
    login_url = "login"

    def form_valid(self, form):
        cli = form.save(commit=False)
        cli.save()

        success_url = reverse('cliente:lista-cliente')

        return HttpResponseRedirect(success_url)


class DetailClientView(LoginRequiredMixin, DetailView):
    model = Client
    template_name = "clientes/detail.html"
    context_object_name = "obj"
    pk_url_kwarg = "id"
    login_url = "login"


class UpdateClientView(LoginRequiredMixin, UpdateView):
    model = Client
    template_name = "clientes/update.html"
    form_class = ClientForm
    pk_url_kwarg = "id"
    context_object_name = 'cli'
    login_url = "login"

    def form_valid(self, form):
        cli = form.save(commit=False)
        cli.save()

        success_url = reverse('cliente:lista-cliente')

        return HttpResponseRedirect(success_url)


def client_disable(request, id):
    cliente = Client.objects.filter(pk=id).first()
    contexto = {}
    template_name = "clientes/disable.html"

    if not cliente:
        return redirect("cliente:lista-cliente")

    if request.method == 'GET':
        contexto = {'obj': cliente}

    if request.method == 'POST':
        cliente.estado = False
        cliente.save()
        messages.success(request, 'Cliente Deshabilitado')
        return redirect("cliente:lista-cliente")

    return render(request, template_name, contexto)


def client_enable(request, id):
    cliente = Client.objects.filter(pk=id).first()
    contexto = {}
    template_name = "clientes/enable.html"

    if not cliente:
        return redirect("cliente:lista-cliente")

    if request.method == 'GET':
        contexto = {'obj': cliente}

    if request.method == 'POST':
        cliente.estado = True
        cliente.save()
        messages.success(request, 'Cliente Habilitado')
        return redirect("cliente:lista-cliente")

    return render(request, template_name, contexto)

client/templates/clientes/create.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %} Agregar Cliente{% endblock%}
{% block css %}
    <style>
        label{
            color: #333;
            font-weight:700;
        }
    </style>
{% endblock %}
{% block content %}
    <form method="POST" >
     {% csrf_token %}
    <div class="">
              <div class="card border-left-success shadow h-100 py-2">
                <div class="card-body">
                  <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                      <div class="text-xs font-weight-bold text-success text-uppercase mb-2"> <h5>Nuevo Cliente</h5></div>

                            {% crispy form %}
                        <br>
                            <button type="submit" class="btn btn-success"> <i class="fa fa-save"></i> Agregar</button>

                    </div>

                  </div>
                </div>
              </div>
            </div>
</form>
{% endblock %}

client/templates/clientes/detail.html
{% extends 'base.html' %}
{% block title %} Detalle Cliente{% endblock%}
{% block css %}
    <style>
    .border-img{
        border: 5px solid #143261 !important;
    }
    </style>
{% endblock %}
{% block content %}
    <div class="card shadow mb-4">
    <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
        <h5  class="m-0 font-weight-bold text-primary">Informacion de {{ obj.apep }} {{ obj.apem }} {{ obj.nombre }}</h5>
        <div class="dropdown no-arrow">
                       {% if perms.client.can_add_client %}
                    <a class="btn btn-outline-danger btn-block" href="{% url 'cliente:pdfexport-cliente-det' obj.pk %}" role="button" target="_blank">
                      <i class="fas fa-file-pdf fa-fw "></i>
                        PDF
                    </a>
                      {% endif %}
                  </div>
    </div>

  <div class="card-body">
      <div class="row">
          <div class="col-md-12 text-right">
              <h5>Estado: <span class="text-primary font-weight-bold">{{ obj.estado|yesno:"Activo,Inactivo" }}</span></h5>
          </div>
      </div>
      <div class="row">
          <div class="col-md-12 text-right">

             <i style="color: black" class=" border-img p-3 fa fa-7x  fa-user"></i>

          </div>
      </div>
          <div class="row">
       <div class="col-md-12">
          <div class="form-group">
                  <label>Direccion: </label>
                  <p class="text-dark font-weight-bold">{{ obj.direccion }} #{{ obj.no_ext }} {{ obj.colonia }}, {{ obj.ciudad }}, {{ obj.cp }}, {{ obj.pais }}</p>
          </div>
       </div>
   </div>

          <div class="row ">
       <div class="col-md-3">
          <div class="form-group">
                  <label>Telefono: </label>
                  <p class="text-dark font-weight-bold ">{{ obj.tel }}</p>
          </div>
       </div>
          <div class="col-md-3">
          <div class="form-group">
                  <label>Email: </label>
                  <p class="text-dark font-weight-bold">{{ obj.email }}</p>
          </div>
       </div>
          <div class="col-md-3">
          <div class="form-group">
                  <label>Documento Oficial: </label>
                  <p class="text-dark font-weight-bold">{{ obj.tipodoc }}</p>
          </div>
       </div>
              <div class="col-md-3">
          <div class="form-group">
                  <label>No de Documento Oficial: </label>
                  <p class="text-dark font-weight-bold">{{ obj.nodocof }}</p>
          </div>
       </div>
   </div>
  </div>
</div>

    <div class="card">
  <h5 class="card-header font-weight-bolder text-primary">Proximo Modulos a Agregar</h5>
  <div class="card-body">

  </div>
</div>
{% endblock %}
{% block js %}

{% endblock %}

client/templates/clientes/disable.html
{% extends "base.html" %}
{% block title %} Deshabilitar Cliente{% endblock%}
{% block content %}
    <form method="POST" >
     {% csrf_token %}
    <div class="">
              <div class="card border-left-danger shadow h-100 py-2">
                <div class="card-body">
                  <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                      <div class="text-xs font-weight-bold text-danger text-uppercase mb-2"> <h5>¿Deshabilitar a {{ obj.apep }} {{ obj.apem }} {{ obj.nombre }}?</h5></div>

                            <button type="submit" class="btn btn-danger"> <i class="fa fa-trash-alt"></i> Si, Deshabilitar</button>
                            <a href="{% url 'cliente:lista-cliente' %}" class="btn btn-outline-secondary " role="button"><i class="fa fa-times"></i> Cancelar</a>


                    </div>

                  </div>
                </div>
              </div>
            </div>
</form>
{% endblock %}

client/templates/clientes/enable.html
{% extends "base.html" %}
{% block title %} Habilitar Cliente{% endblock%}
{% block content %}
    <form method="POST" >
     {% csrf_token %}
    <div class="">
              <div class="card border-left-success shadow h-100 py-2">
                <div class="card-body">
                  <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                      <div class="text-xs font-weight-bold text-success text-uppercase mb-2"> <h5>¿Habilitar a {{ obj.apep }} {{ obj.apem }} {{ obj.nombre }}?</h5></div>

                            <button type="submit" class="btn btn-success"> <i class="fa fa-check"></i> Si, Habilitar</button>
                            <a href="{% url 'cliente:lista-cliente' %}" class="btn btn-outline-secondary " role="button"><i class="fa fa-times"></i> Cancelar</a>


                    </div>

                  </div>
                </div>
              </div>
            </div>
</form>
{% endblock %}

client/templates/clientes/index.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Clientes{% endblock %}
{% block css %}
    <style>
        .illustration {
            display: block;
            margin-left: auto;
            margin-right: auto;
            width: 801px;
            height: 632px;
            background: url({% static 'img/undraw_empty_xct9.svg' %});
            background-size: cover;
        }
    </style>
{% endblock %}
{% block content %}
    {% if messages %}
        <div class=" alert alert-success alert-dismissible fade show" role="alert">
            {% for message in messages %}
                {{ message }}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            {% endfor %}
        </div>
    {% endif %}
    <div class="card shadow mb-4">
        <!-- Card Header - Dropdown -->
        <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
            <h4 class="m-0 font-weight-bold text-primary">Clientes</h4>
            <div class="dropdown no-arrow">
                {% if perms.client.can_add_client %}
                    <a class="btn btn-success btn-block" href="{% url 'cliente:agregar-cliente' %}" role="button">
                        <i class="fas fa-plus fa-sm fa-fw "></i>
                        Agregar
                    </a>
                {% endif %}
            </div>
        </div>
        <!-- Card Body -->
        <div class="card-body">
            {% if not obj %}
                <div class="col-md-12">
                    <h2 class="font-weight-bold text-center">No hay clientes</h2>
                    <div class="illustration"></div>
                </div>
            {% else %}
                <div class="col-md-6 mb-3 pl-0">

                    <a class="btn btn-outline-brand-excel" href="{% url 'cliente:xlsexport-cliente' %}" role="button">
                        <i class="fas fa-file-excel fa-fw "></i>
                        Excel
                    </a>
                    <a class="btn btn-outline-brand-google" href="{% url 'cliente:pdfexport-cliente' %}" role="button" target="_blank">
                        <i class="fas fa-file-pdf fa-fw "></i>
                        PDF
                    </a>
                </div>
                <table class="table table-striped table-hover text-center table-responsive">
                    <thead class="thead-primary">
                    <tr>
                        <th>ID</th>
                        <th>Nombre</th>
                        <th>Documento Oficial</th>
                        <th>No. Doc. Oficial</th>
                        <th>Fecha de Ingreso</th>
                        <th>Estado</th>
                        <th class="all">Acciones</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for item in obj %}
                        <tr>
                            <td>{{ item.id }}</td>
                            <td>{{ item.apep }} {{ item.apem }} {{ item.nombre }}</td>
                            <td>{{ item.tipodoc }}</td>
                            <td>{{ item.nodocof }}</td>
                            <td>{{ item.fc }}</td>
                            <td>{{ item.estado|yesno:"Activo,Inactivo" }}</td>
                            <td>
                                <div class="row ">
                                    <a href="{% url 'cliente:detail-cliente' item.id %}"
                                       class="btn btn-sm btn-info mr-1" role="button"><i class="fa fa-eye"></i></a>
                                    {% if perms.client.can_edit_client %}
                                        <a href="{% url 'cliente:update-cliente' item.id %}"
                                           class="btn btn-sm btn-warning mr-1 " role="button"><i class="fa fa-edit"></i></a>
                                    {% endif %}
                                    {% if item.estado != False %}
                                        <a href="{% url 'cliente:disable-cliente' item.id %}"
                                           class="btn btn-sm btn-danger mr-1" role="button"><i
                                                class="fa fa-trash-alt"></i></a>
                                    {% else %}
                                        <a href="{% url 'cliente:enable-cliente' item.id %}"
                                           class="btn btn-sm btn-success mr-1" role="button"><i class="fa fa-check"></i></a>
                                    {% endif %}
                                </div>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            {% endif %}
        </div>
    </div>
{% endblock %}
{% block js %}
    <script>
        // Call the dataTables jQuery plugin
        $(document).ready(function () {
            $('.table').DataTable({
                "language": {
                    "sProcessing": "Procesando...",
                    "sLengthMenu": "Mostrar _MENU_ registros",
                    "sZeroRecords": "No se encontraron resultados",
                    "sEmptyTable": "Ningún dato disponible en esta tabla",
                    "sInfo": "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
                    "sInfoEmpty": "Mostrando registros del 0 al 0 de un total de 0 registros",
                    "sInfoFiltered": "(filtrado de un total de _MAX_ registros)",
                    "sInfoPostFix": "",
                    "sSearch": "Buscar:",
                    "sUrl": "",
                    "sInfoThousands": ",",
                    "sLoadingRecords": "Cargando...",
                    "oPaginate": {
                        "sFirst": "<span class='fa fa-angle-double-left'></span>",
                        "sLast": "<span class='fa fa-angle-double-right'></span>",
                        "sNext": "<span class='fa fa-angle-right'></span>",
                        "sPrevious": "<span class='fa fa-angle-left'></span>"
                    },
                    "oAria": {
                        "sSortAscending": ": Activar para ordenar la columna de manera ascendente",
                        "sSortDescending": ": Activar para ordenar la columna de manera descendente"
                    }
                }
            });
        });
    </script>
{% endblock %}

client/templates/clientes/pdfdetail.html
<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <title>Reporte de Clientes</title>
    <style type="text/css">
        @page {
            size: A4;
            margin: 1cm;
        }

        .title{
            text-align: center;
            font-size: 2em;
        }

        .subtitle{
            text-align: center;
            font-size: 1.5em;
        }

        .table {
            width: 100%;
            max-width: 100%;
            margin-bottom: 5px;
            background-color: #fff;
        }

        .table th,
        .table td {
            padding: 5px;
            vertical-align: top;
            border-top: 1px solid #000;
            text-align: center;
        }

        .table thead th {
            vertical-align: bottom;
            border-bottom: 2px solid #000;
        }

        .table tbody + tbody {
            border-top: 2px solid #000;
        }

        .table .table {
            background-color: #fff;
        }

        .list-group {
            display: block;
            width: 100%;
            list-style: none;
            margin-top: 15px;
            margin-bottom: 15px;
        }

        .list-group p {
            width: 100%;
            height: 20px;
            line-height: 20px;
            list-style: none;
            font-size: 1.1em;
        }

    </style>
</head>
<body>

<div class="container">
    <div class="card">
        <div class="card-header">
            <h1 class="title">Seguro de las Californias</h1>
        </div>

        <div class="list-group">
            <h3 class="subtitle">Reporte de Clientes - {{ today | date:"d/m/Y" }}</h3>
        </div>

        <table class="table">
            <thead>
            <tr>
                <th>ID</th>
                <th>Nombre</th>
                <th>Documento Oficial</th>
                <th>No. Doc. Oficial</th>
                <th>Fecha de Ingreso</th>
                <th>Estado</th>
            </tr>
            </thead>
            <tbody>
            {% for item in clients %}
                        <tr>
                        <td>{{ item.id }}</td>
                        <td>{{ item.apep }} {{ item.apem }} {{ item.nombre }}</td>
                        <td>{{ item.tipodoc }}</td>
                            <td>{{ item.nodocof }}</td>
                            <td>{{ item.fc }}</td>
                            <td>{{ item.estado|yesno:"Activo,Inactivo"}}</td>
                        </tr>
                    {% endfor %}
            </tbody>
        </table>
    </div>
</div>

</body>
</html>

client/templates/clientes/pdfdetails.html
<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <title>Reporte de Cliente</title>
    <style type="text/css">
        @page {
            size: A4;
            margin: 0;
        }

        .card-header{
            background-color:#0e1a33;
            color: white;
            height:100px;
            padding: 50px;
        }

        .title{
            text-align: center;
            font-size: 2.5em;

        }

        .subtitle{
            text-align: center;
            font-size: 2.0em;
        }

        .text{
            font-size: 1.5em;
            margin: 1cm;
        }

        .table {
            width: 100%;
            max-width: 100%;
            margin-bottom: 5px;
            background-color: #fff;
        }

        .table th,
        .table td {
            padding: 5px;
            vertical-align: top;
            border-top: 1px solid #000;
            text-align: center;
        }

        .table thead th {
            vertical-align: bottom;
            border-bottom: 2px solid #000;
        }

        .table tbody + tbody {
            border-top: 2px solid #000;
        }

        .table .table {
            background-color: #fff;
        }

        .list-group {
            display: block;
            width: 100%;
            list-style: none;
            margin-top: 15px;
            margin-bottom: 15px;
        }

        .list-group p {
            width: 100%;
            height: 20px;
            line-height: 20px;
            list-style: none;
            font-size: 1.1em;
        }

    </style>
</head>
<body>

<div class="container">
    <div class="card">
        <div class="card-header">
            <h1 class="title">Seguro de las Californias</h1>
        </div>

        <div class="list-group">
            <h3 class="subtitle">Reporte de Cliente {{ clientdet.id }} - {{ today | date:"d/m/Y" }}</h3>
        </div>

        <div class="row">
            <h3 class="text"> Nombre: <span> {{ clientdet.apep }} {{ clientdet.apem }} {{ clientdet.nombre }}</span></h3>
            <h3 class="text"> Direccion: <span> {{ clientdet.direccion }} #{{ clientdet.no_ext }} {{ clientdet.colonia }}, {{ clientdet.ciudad }}, {{ clientdet.cp }}, {{ clientdet.pais }}</span></h3>
            <h3 class="text"> No. Telefono: <span> {{ clientdet.tel }}</span></h3>
            <h3 class="text"> Email: <span> {{ clientdet.email }}</span></h3>
            <h3 class="text"> Documento Oficial: <span> {{ clientdet.tipodoc }}</span></h3>
            <h3 class="text"> No. Documento Oficial: <span> {{ clientdet.nodocof }}</span></h3>
        </div>

    </div>
</div>

</body>
</html>

client/templates/clientes/update.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %} Editar Cliente{% endblock%}
{% block content %}
    <form method="POST" >
     {% csrf_token %}
    <div class="">
              <div class="card border-left-warning shadow h-100 py-2">
                <div class="card-body">
                  <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                      <div class="text-xs font-weight-bold text-warning text-uppercase mb-2"> <h5>Editar Cliente</h5></div>

                            {% crispy form %}
                        <br>
                            <button type="submit" class="btn btn-warning"> <i class="fa fa-save"></i> Editar</button>

                    </div>

                  </div>
                </div>
              </div>
            </div>
</form>
{% endblock %}